import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from "next/head";
import styles from "../styles/Home.module.css";
import algoliasearch from "algoliasearch/lite";
import { InstantSearch, RefinementList } from "react-instantsearch-hooks-web";

const searchClient = algoliasearch(
  process.env.NEXT_PUBLIC_ID || "",
  process.env.NEXT_PUBLIC_KEY || " "
);

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Job-search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <InstantSearch
          searchClient={searchClient}
          indexName={process.env.NEXT_PUBLIC_INDEX_NAME || ""}
        >
          <Component {...pageProps} />
        </InstantSearch>
      </main>
    </div>
  );
}
